name: com
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  url_launcher: ^6.2.2

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/expertise/
